### ISSUE TITLE
Loading screen is broken by spamming create account

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#137] opened 2021-12-05 12:41 UTC
![image](https://user-images.githubusercontent.com/68207888/144746967-f5fd1dbe-5233-499d-a4a8-b7048f5e7825.png)

**Comment by definitely-nobody-is-here** [comment] 2021-12-05 14:42
Duplicate of #136

**Closed** 2021-12-11 22:10 UTC
Labels: bug, duplicate, done
