### ISSUE TITLE
Two staffs???

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#153] opened 2021-12-23 23:30 UTC
![image](https://user-images.githubusercontent.com/68207888/147299372-e72f7a62-c303-451d-a2b9-9dab7c5f75f5.png)

**Comment by definitely-nobody-is-here** [comment] 2021-12-24 15:17
that's impossible. How did you do it? I feel like this is a rendering problem and not an inventory problem since the helditem is one object and can only hold one id

**Comment by maitian352** [comment] 2021-12-24 21:37
Yeah, it might be a rendering bug. I didn't hold two items.

**Comment by definitely-nobody-is-here** [comment] 2022-01-03 00:46
what did you do to get this result? Is it reproducable?

**Comment by definitely-nobody-is-here** [comment] 2022-01-06 02:15
If not confirmed within 30 days it will be closed.

**Comment by definitely-nobody-is-here** [comment] 2022-01-07 18:57
15 days left

**Comment by maitian352** [comment] 2022-01-11 02:30
![image](https://user-images.githubusercontent.com/68207888/148870882-bfc97be1-a40c-4739-b940-46ae86bf7333.png)
Just happened again!

**Comment by definitely-nobody-is-here** [comment] 2022-01-12 22:09
You dropped an item didn't you.

**Comment by definitely-nobody-is-here** [comment] 2022-01-19 18:25
3 days left to confirm

**Comment by definitely-nobody-is-here** [comment] 2022-05-03 17:26
This hasn't been confirmed. The issue will be closed and marked as invalid.

**Closed by definitely-nobody-is-here** 2022-05-03 17:26 UTC
Labels: bug, invalid, question, wontfix, please confirm
