### ISSUE TITLE
Invalid layer with monsters

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#213] opened 2022-01-13 02:36 UTC
![image](https://user-images.githubusercontent.com/68207888/149255860-eee3908f-263f-4895-8785-ea75ad3c7cf3.png)

**Comment by maitian352** [comment] 2022-01-13 02:39
![image](https://user-images.githubusercontent.com/68207888/149256100-137ef1ac-482b-4bc5-86b4-5ab2dbcb1917.png)
They just go down the staircase and break

**Comment by definitely-nobody-is-here** [comment] 2022-01-15 17:17
Duplicate of #197

**Comment by definitely-nobody-is-here** [comment] 2022-01-19 19:38
I think I fixed the monsters having invalid layers? They can cross the bridge fine now.

**Comment by maitian352** [comment] 2022-01-19 20:12
No, is monsters going down stairs.

**Comment by definitely-nobody-is-here** [comment] 2022-01-19 20:13
The bridge has stairs

**Comment by maitian352** [comment] 2022-01-19 20:15
On the bridge can monsters go through collisions?

**Comment by definitely-nobody-is-here** [comment] 2022-01-20 18:43
no

**Comment by definitely-nobody-is-here** [comment] 2022-01-21 01:31
![image](https://user-images.githubusercontent.com/67865358/150449183-f2ac78fd-9232-4e77-a0b2-f8be6fc035ef.png)
hmmmmmm

**Comment by definitely-nobody-is-here** [comment] 2022-03-19 00:58
Issue Fixed in v0.9.0

**Closed by definitely-nobody-is-here** 2022-03-19 00:58 UTC
Labels: bug, duplicate, hard, done
