### ISSUE TITLE
Monster dumb?

### ISSUE THREAD

**Issue by maitian352** [definitely-nobody-is-here/Mountain_Guarder#148] opened 2021-12-23 23:22 UTC
Why is it not attacking me? I have debug open and there is no red ring.
![image](https://user-images.githubusercontent.com/68207888/147299071-9ff965ae-f855-4850-8a76-ba3fd9152f96.png)

**Comment by maitian352** [comment] 2021-12-23 23:23
Seriously...
![image](https://user-images.githubusercontent.com/68207888/147299088-aeb1d1b8-dcab-4e3c-8176-b2984d725919.png)

**Comment by maitian352** [comment] 2021-12-23 23:23
My projectiles are not homing on them.

**Comment by definitely-nobody-is-here** [comment] 2021-12-24 15:25
this is a known bug. At gridx=0 things stop working

**Comment by definitely-nobody-is-here** [comment] 2021-12-24 15:25
Duplicate of #142

**Comment by maitian352** [comment] 2021-12-26 02:24
No, like every monster in the bottom is not working.

**Comment by maitian352** [comment] 2021-12-29 19:02
![image](https://user-images.githubusercontent.com/68207888/147695025-90571af5-3e6b-4f7b-931b-c08901743fc6.png)

**Closed** 2022-01-05 03:03 UTC
Labels: bug, duplicate, hard, done
